name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"
      - name: Show Python
        run: python3 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest -q --cov=prediction_pipeline_demo --cov-report=term-missing --cov-fail-under=70

      - name: Run prediction pipeline demo (end-to-end test)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python prediction_pipeline_demo.py
      # TODO: Add a step here to run the demo pipeline end-to-end
      # The goal is to execute prediction_pipeline_demo.py so CI logs show the model’s R^2 score.